import React, { useContext } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useQuery, gql } from '@apollo/client'
import Link from 'next/link'
import PostList from '../components/PostList'
import { AuthContext } from '../context/auth'
import PostForm from '../components/PostForm'

export const FETCH_POSTS_QUERY = gql`
query {
    getPosts {
      id
      body
      username
      commentCount
      comments {
        id
        username
        body
      }
    }
  }
`


export default function Home() {
  const ctx = useContext(AuthContext)
  const { loading, data } = useQuery(FETCH_POSTS_QUERY)

  const logoutHandler = () => {
    ctx.logout()
  }

  if (loading) {
    return <p>loading...</p>
  }
  const { getPosts: posts } = data
  if (!posts) {
    <p>no posts...</p>
  }
  if (ctx.user) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
            <button type='button' onClick={logoutHandler} >Logout</button>
          </div>
          <PostList posts={posts} />
          <PostForm />
        </main>
      
      </div>
    )
  } else {
    return (
      <div>
      <Link href='/signup'>
      <a>Signup</a>
    </Link>
    <Link href='/login'>
      <a>Login</a>
    </Link>
      </div>
    )
  }
  
}
